# tryfolder.yml
---
- name: Create main folder and subfolders, convert syslog to CSV, and copy to sub1
  hosts: localhost
  
  vars:
    main_folder_path: "./SYSLOG/"
    script_path: "./convert_syslog.py"

  tasks:
    - name: Create main folder
      file:
        path: "{{ main_folder_path }}"
        state: directory

    - name: Create subfolder END DEVICE
      file:
        path: "{{ main_folder_path }}/END DEVICE"
        state: directory

    - name: Create subfolder INTERMEDIARY DEVICE
      file:
        path: "{{ main_folder_path }}/INTERMEDIARY DEVICE"
        state: directory

    - name: Copy Python script to local machine
      copy:
        src: "convert_syslog.py"
        dest: "{{ script_path }}"
        mode: '0755'

    - name: Convert syslog to CSV using Python script
      command: python3 "{{ script_path }}"
      args:
        creates: "{{ main_folder_path }}/END DEVICE/end-device_syslog.csv"
    #copys
    - name: Copy syslog.csv file to END DEVICE
      copy:
        src: "{{ main_folder_path }}/END DEVICE/end-device_syslog.csv"
        dest: "{{ main_folder_path }}/END DEVICE/end-device_syslog.csv"