---
- name: Create main folder and subfolders, convert syslog to CSV, and copy to sub1
  hosts: all  # Change to 'all' to apply to all hosts in the inventory

  vars:
    main_folder_path: "./SYSLOG/"
    script_path: "./convert_syslog.py"

  tasks:
    - name: Create main folder
      file:
        path: "{{ main_folder_path }}"
        state: directory

    - name: Create subfolder END DEVICE
      file:
        path: "{{ main_folder_path }}/END DEVICE"
        state: directory

    - name: Create subfolder INTERMEDIARY DEVICE
      file:
        path: "{{ main_folder_path }}/INTERMEDIARY DEVICE"
        state: directory

    - name: Copy Python script to remote machine
      copy:
        src: "convert_syslog.py"
        dest: "{{ script_path }}"
        mode: '0755'

    - name: Convert syslog to CSV using Python script on remote machine
      command: python3 "{{ script_path }}"
      args:
        chdir: "{{ main_folder_path }}/END DEVICE/"
        creates: "end-device_syslog.csv"

    - name: Copy syslog.csv file from remote machine to END DEVICE folder
      fetch:
        src: "{{ main_folder_path }}/END DEVICE/end-device_syslog.csv"
        dest: "{{ main_folder_path }}/END DEVICE/"
